language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1

gemfile:
  - Gemfile

services:
  - mongodb

env:
  - CODECLIMATE_REPO_TOKEN=b216164ab66da464aa02fe5b862811ba0526c8dc7ea291ebe53056be4b6b5e1f

script: "bundle exec rspec"
